spring.application.name=socialfeed

spring.data.mongodb.uri=mongodb://localhost:27017/social_feed_db

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
